-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local function augroup(name)
--   return vim.api.nvim_create_augroup("lazyvim_" .. name, { clear = true })
-- end
--
-- vim.api.nvim_create_autocmd({ "FileType" }, {
--   group = augroup("my_roslyn"),
--   pattern = "cs",
--   callback = function(ev)
--     print("AU callback")
--     vim.lsp.start({
--       name = "my-roslyn",
--       cmd = {
--         "/home/mnj/code/private/roslyn-ls-wrapper/source/roslyn-ls-wrapper.App/bin/Debug/net8.0/roslyn-ls-wrapper",
--       },
--       root_dir = vim.fs.root(ev.buf, function(name)
--         return name:match("%.sln$") ~= nil
--       end),
--       filetypes = { "cs" },
--     })
--   end,
-- })
