return {
  -- {
  -- 	"RRethy/base16-nvim",
  -- 	priority = 1000,
  -- 	config = function()
  -- 		require('base16-colorscheme').setup({
  -- 			base00 = '#100F0F',
  -- 			base01 = '#100F0F',
  -- 			base02 = '#5c6370',
  -- 			base03 = '#5c6370',
  -- 			base04 = '#abb2bf',
  -- 			base05 = '#ffffff',
  -- 			base06 = '#ffffff',
  -- 			base07 = '#ffffff',
  -- 			base08 = '#e05f95',
  -- 			base09 = '#e05f95',
  -- 			base0A = '#ffbcac',
  -- 			base0B = '#aee086',
  -- 			base0C = '#a56858',
  -- 			base0D = '#ffbcac',
  -- 			base0E = '#b95b5e',
  -- 			base0F = '#b95b5e',
  -- 		})
  --
  -- 		vim.api.nvim_set_hl(0, 'Visual', {
  -- 			bg = '#5c6370',
  -- 			fg = '#ffffff',
  -- 			bold = true
  -- 		})
  -- 		vim.api.nvim_set_hl(0, 'Statusline', {
  -- 			bg = '#ffbcac',
  -- 			fg = '#100F0F',
  -- 		})
  -- 		vim.api.nvim_set_hl(0, 'LineNr', { fg = '#5c6370' })
  -- 		vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#a56858', bold = true })
  --
  -- 		vim.api.nvim_set_hl(0, 'Statement', {
  -- 			fg = '#b95b5e',
  -- 			bold = true
  -- 		})
  -- 		vim.api.nvim_set_hl(0, 'Keyword', { link = 'Statement' })
  -- 		vim.api.nvim_set_hl(0, 'Repeat', { link = 'Statement' })
  -- 		vim.api.nvim_set_hl(0, 'Conditional', { link = 'Statement' })
  --
  -- 		vim.api.nvim_set_hl(0, 'Function', {
  -- 			fg = '#ffbcac',
  -- 			bold = true
  -- 		})
  -- 		vim.api.nvim_set_hl(0, 'Macro', {
  -- 			fg = '#ffbcac',
  -- 			italic = true
  -- 		})
  -- 		vim.api.nvim_set_hl(0, '@function.macro', { link = 'Macro' })
  --
  -- 		vim.api.nvim_set_hl(0, 'Type', {
  -- 			fg = '#a56858',
  -- 			bold = true,
  -- 			italic = true
  -- 		})
  -- 		vim.api.nvim_set_hl(0, 'Structure', { link = 'Type' })
  --
  -- 		vim.api.nvim_set_hl(0, 'String', {
  -- 			fg = '#aee086',
  -- 			italic = true
  -- 		})
  --
  -- 		vim.api.nvim_set_hl(0, 'Operator', { fg = '#abb2bf' })
  -- 		vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#abb2bf' })
  -- 		vim.api.nvim_set_hl(0, '@punctuation.bracket', { link = 'Delimiter' })
  -- 		vim.api.nvim_set_hl(0, '@punctuation.delimiter', { link = 'Delimiter' })
  --
  -- 		vim.api.nvim_set_hl(0, 'Comment', {
  -- 			fg = '#5c6370',
  -- 			italic = true
  -- 		})
  --
  -- 		local current_file_path = vim.fn.stdpath("config") .. "/lua/plugins/dankcolors.lua"
  -- 		if not _G._matugen_theme_watcher then
  -- 			local uv = vim.uv or vim.loop
  -- 			_G._matugen_theme_watcher = uv.new_fs_event()
  -- 			_G._matugen_theme_watcher:start(current_file_path, {}, vim.schedule_wrap(function()
  -- 				local new_spec = dofile(current_file_path)
  -- 				if new_spec and new_spec[1] and new_spec[1].config then
  -- 					new_spec[1].config()
  -- 					print("Theme reload")
  -- 				end
  -- 			end))
  -- 		end
  -- 	end
  -- }
}
