[user]
name = "Marcin Jahn"
email = "10273406+marcinjahn@users.noreply.github.com"

[template-aliases]
'format_short_id(id)' = 'id.shortest()'

[ui]
default-command = "log"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = ["-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right"]
merge-tool-edits-conflict-markers = true

[git]
push-new-bookmarks = true
