"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = '[>:](bold green)'
error_symbol = '[>:](bold red)'

[dotnet]
disabled = true
detect_extensions = ['sln', 'csproj', 'fsproj', 'xproj']

[gcloud]
disabled = true